const rawData = "btech present usa";
const domains = {
      arts_humanities_social_sciences: { score: 0, keywords: ["bachelor of arts", "ba", "b.a", "bachelor of social work", "bsw", "bachelor of fine arts", "bfa", "bachelor of design", "b.des", "master of arts", "ma", "m.a", "master of social work", "msw", "master of fine arts", "mfa", "master of design", "m.des", "master of library and information science", "mlis", "master of public administration", "mpa", "master of international relations", "mir", "master of development studies", "arts", "humanities", "social sciences", "history", "philosophy", "sociology", "political science", "literature", "languages", "anthropology", "geography", "psychology", "economics", "english", "library science", "linguistics", "cultural studies", "applied arts", "painting", "sculpture", "visual communication", "textile design", "ceramic design", "interior design", "fashion design", "game design", "industrial design", "clinical social work", "community development", "child welfare"] },
      commerce_management: { score: 0, keywords: ["bachelor of commerce", "b.com", "bcom", "bachelor of business administration", "bba", "bachelor of management studies", "bms", "master of commerce", "m.com", "mcom", "master of business administration", "mba", "master of management studies", "mms", "executive mba", "emba", "commerce", "management", "business", "finance", "marketing", "accounting", "hr", "sales", "entrepreneurship", "human resource management", "international business", "banking", "insurance", "supply chain management", "logistics", "operations management", "taxation", "business analytics", "retail management", "e-commerce", "event management", "healthcare management"] },
      science_technology: { score: 0, keywords: ["bachelor of science", "b.sc", "bsc", "bachelor of computer applications", "bachelor of computer application", "computer application", "computer applications", "bca", "bachelor of technology", "b.tech", "btech", "bachelor of engineering", "b.e", "be", "master of data science", "mds", "master of artificial intelligence", "mai", "master of environmental management", "mem", "master of science", "m.sc", "msc", "master of technology", "m.tech", "mtech", "master of engineering", "m.e", "me", "master of computer applications", "master of computer application", "mca", "science", "technology", "computer science", "it", "engineering", "software", "physics", "chemistry", "mathematics", "biology", "data", "ai", "information technology", "artificial intelligence", "machine learning", "data science", "cybersecurity", "software engineering", "cloud computing", "mechanical engineering", "civil engineering", "electrical engineering", "electronics and communication", "chemical engineering", "aerospace engineering", "robotics", "mechatronics", "biotechnology", "microbiology", "genetics", "zoology", "botany", "environmental science", "statistics", "geology", "food technology", "bioinformatics"] },
      medicine_allied_health: { score: 0, keywords: ["bachelor of dental science", "bachelor of surgery", "mbbs", "bachelor of dental surgery", "bds", "bachelor of ayurvedic medicine and surgery", "bams", "bachelor of homeopathic medicine and surgery", "bhms", "bachelor of physiotherapy", "bpt", "bachelor of science in nursing", "b.sc nursing", "bachelor of pharmacy", "b.pharm", "doctor of medicine", "md", "master of surgery", "ms", "master of dental surgery", "mds", "master of pharmacy", "m.pharm", "master of physiotherapy", "mpt", "master of public health", "mph", "master of science in nursing", "m.sc nursing", "nursing", "medicine", "health", "pharmacy", "dentistry", "public health", "physiotherapy", "allied health", "general medicine", "general surgery", "pediatrics", "orthopedics", "obstetrics", "gynecology", "dermatology", "psychiatry", "anesthesia", "radiology", "cardiology", "neurology", "oncology", "gastroenterology", "nephrology", "urology", "ophthalmology", "ent", "clinical research", "pharmacology", "pharmaceutics", "pharmacognosy", "toxicology", "orthodontics", "periodontics", "prosthodontics", "oral surgery", "ayurveda", "homeopathy", "unani"] },
      law: { score: 0, keywords: ["bachelor of law", "llb", "master of laws", "llm", "law", "legal", "jurisprudence", "criminology", "corporate law", "criminal law", "civil law", "international law", "constitutional law", "intellectual property law", "labor law", "environmental law", "family law", "human rights law", "cyber law", "tax law"] },
      education: { score: 0, keywords: ["bachelor of education", "b.ed", "bed", "master of education", "m.ed", "med", "master of arts in education", "ma education", "education", "teaching", "pedagogy", "curriculum", "special education", "early childhood education", "primary education", "secondary education", "educational leadership", "educational psychology", "physical education"] },
      hospitality_tourism_events: { score: 0, keywords: ["bachelor of hotel management", "bhm", "bachelor of tourism studies", "bts", "master of hotel management", "mhm", "master of tourism administration", "mta", "hospitality", "tourism", "events", "hotel management", "culinary", "travel", "hospitality administration", "culinary arts", "catering technology", "travel and tourism management", "event management", "aviation management", "cruise line management"] },
      performing_arts_media: { score: 0, keywords: ["bachelor of mass media", "bmm", "bachelor of journalism and mass communication", "bjmc", "bachelor of performing arts", "bpa", "bachelor of physical education", "bped", "master of journalism and mass communication", "mjmc", "master of physical education", "mped", "master of performing arts", "performing arts", "media", "journalism", "film", "music", "dance", "theatre", "mass communication", "broadcasting", "public relations", "advertising", "media studies", "film studies", "cinematography", "video editing", "sound engineering", "animation", "visual effects", "vocal music", "instrumental music", "acting", "directing"] },
      agriculture_veterinary: { score: 0, keywords: ["bachelor of agriculture", "b.sc agriculture", "bachelor of veterinary science", "b.v.sc", "bvsc", "msc agriculture", "mvsc", "agriculture", "veterinary", "agronomy", "forestry", "animal science", "horticulture", "vet", "plant pathology", "agricultural economics", "agricultural extension", "soil science", "entomology", "genetics and plant breeding", "food science", "dairy technology", "agricultural engineering", "veterinary science", "animal husbandry", "animal genetics", "veterinary microbiology", "veterinary pathology", "veterinary surgery"] }
};
Object.keys(domains).forEach(key => {
  const d = domains[key];
  d.keywords.forEach(kw => {
    const safeKw = kw.replace(/\./g, '\\.');
    const regex = new RegExp(`\\b${safeKw}\\b`, 'gi');
    const matches = rawData.match(regex);
    if (matches) {
      let weight = 1;
      if (kw.includes("bachelor") || kw.includes("master") || kw.length <= 4) weight = 10;
      if (["arts", "science", "commerce", "management", "history", "english", "languages", "data", "it", "media"].includes(kw)) weight = 1;
      d.score += (matches.length * weight);
      console.log(`Matched ${kw} in ${key} with weight ${weight}`);
    }
  });
});
let primaryDomain = "science_technology";
let maxScore = 0;
Object.entries(domains).forEach(([domain, data]) => {
  if (data.score > maxScore) {
    maxScore = data.score;
    primaryDomain = domain;
  }
});
console.log(primaryDomain);
